export type Difficulty = "easy" | "medium" | "hard";

export const textPools: Record<Difficulty, string[]> = {
  easy: [
    "The quick brown fox jumps over the lazy dog and runs away into the forest, where it finds a warm den to rest for the night.",
    "Cats and dogs are popular pets around the world. Many people love to have them as companions in their homes.",
    "The sun rises in the east and sets in the west every single day, bringing light and warmth to all living things on Earth.",
    "She sells sea shells by the sea shore, and the shells she sells are surely sea shells, I am sure.",
    "A simple life is often the best life we can live, with good food, clean water, and kind friends around us.",
    "The rain falls gently on the green leaves, making a soft sound that fills the quiet air of the early morning.",
    "Every day is a new chance to learn something fresh and grow as a person who cares about others.",
    "Birds fly high in the blue sky, searching for food and building nests for their little ones to stay safe.",
    "My favorite season is autumn because the leaves turn red and gold, and the air becomes crisp and cool.",
    "Reading books before bedtime helps calm the mind and leads to better sleep throughout the night.",
    "Exercise is good for both the body and the mind, as it releases chemicals that make us feel happy and strong.",
    "The ocean is home to countless creatures, from tiny plankton to massive whales that sing beautiful songs.",
    "Plants need sunlight, water, and soil to grow tall and healthy, just like people need love and care to thrive.",
    "A warm cup of tea on a cold, rainy day can bring comfort and peace to anyone feeling tired or stressed.",
    "Laughter is the best medicine because it brings people together and makes even the worst days feel brighter.",
  ],
  medium: [
    "The ability to focus deeply on difficult tasks is becoming increasingly rare, yet increasingly valuable in our distracted world.",
    "Successful people are not those who never fail, but those who learn from every mistake and keep moving forward with purpose.",
    "Programming is the art of telling another human what one wants the computer to do in a language both can understand.",
    "The most dangerous phrase in language is 'we have always done it this way,' because it prevents all innovation.",
    "Reading fiction develops empathy by allowing us to inhabit the minds and experiences of characters vastly different from ourselves.",
    "Creativity is not about having original ideas, but about connecting existing ideas in ways that nobody has thought of before.",
    "The greatest challenge of the information age is not access to data, but developing the wisdom to interpret it correctly.",
    "Time management is ultimately life management, because how we spend our hours reflects what truly matters to us as individuals.",
    "Effective communication requires listening more than speaking and understanding more than being understood by others.",
    "The best teachers inspire curiosity rather than providing answers, because questions lead to deeper learning than memorization.",
    "Confidence comes not from always being right, but from being unafraid to be wrong and learning from the experience.",
    "Procrastination is not a time management problem, but an emotional regulation problem rooted in fear of imperfection.",
    "Minimalism is not about having less, but about making room for more of what truly brings meaning and happiness to life.",
    "Gratitude transforms ordinary moments into celebrations by shifting focus from what we lack to what we already possess.",
    "The quality of your relationships determines the quality of your life, more than wealth, status, or achievements ever could.",
  ],
  hard: [
    "The juxtaposition of asymmetric cryptographic algorithms with quantum-resistant protocols demonstrates the extraordinary complexity of modern cybersecurity infrastructure.",
    "Philosophical epistemology examines the nature, justification, and rationality of knowledge and belief, distinguishing between a priori and a posteriori cognition.",
    "The electromagnetic spectrum encompasses radio waves, microwaves, infrared, visible, ultraviolet, X-rays, and gamma rays, each with unique wavelength frequencies.",
    "Neural plasticity refers to the brain's extraordinary capacity to reorganize itself by forming new synaptic connections throughout an individual's lifetime.",
    "Socioeconomic inequality perpetuates intergenerational poverty cycles through systemic barriers that limit upward mobility in stratified contemporary capitalist societies.",
    "The anthropic principle suggests that cosmological constants appear fine-tuned for consciousness, because only in such universes can observers exist to measure them.",
    "Existential phenomenology, as developed by Heidegger and Merleau-Ponty, emphasizes embodied, situated experience over Cartesian dualistic frameworks of mind and body.",
    "The halting problem demonstrates that no general algorithm can determine whether arbitrary computer programs will finish running or continue indefinitely.",
    "Metacognitive strategies involve monitoring and regulating one's own cognitive processes, including planning, evaluation, and reflection during learning tasks.",
    "The prisoner's dilemma illustrates how individual rational decision-making can lead to collectively suboptimal outcomes in game theory scenarios.",
    "Neuroplasticity diminishes with age but can be maintained through continuous learning, challenging novel tasks, and aerobic exercise throughout life.",
    "Cognitive dissonance theory explains the psychological discomfort experienced when holding contradictory beliefs, values, or attitudes simultaneously.",
    "The hedonic treadmill suggests humans quickly return to relatively stable levels of happiness despite major positive or negative life changes.",
    "Pareto efficiency in welfare economics describes allocations where no individual can be made better off without making at least one other worse off.",
    "The Dunning-Kruger effect describes how individuals with low ability at a task overestimate their competence, while experts underestimate their expertise.",
    "Epigenetic modifications influence gene expression without altering DNA sequences, enabling environmental factors to shape inherited biological traits.",
    "The butterfly effect in chaos theory demonstrates that small variations in initial conditions can produce dramatically divergent outcomes in dynamical systems.",
    "Hermeneutic circles describe the recursive process of understanding parts through the whole and the whole through its parts in textual interpretation.",
    "The precautionary principle advocates for preventative action in the face of scientific uncertainty, when potential risks to public health are plausible.",
    "Pareto optimality fails to account for distributive justice, since multiple Pareto efficient allocations can feature extreme wealth inequality between groups.",
  ],
};

export function getRandomText(difficulty: Difficulty): string {
  const pool = textPools[difficulty];
  return pool[Math.floor(Math.random() * pool.length)];
}
