export type Difficulty = "easy" | "medium" | "hard";

export const textPools: Record<Difficulty, string[]> = {
  easy: [
    // Pokemon
    "Ash left Pallet Town with his new partner Pikachu by his side. Professor Oak had given him the electric mouse after all the starter Pokemon were taken. Together they set off to catch Pokemon and earn eight gym badges.",
    // Mario
    "Mario jumped over the first Goomba and grabbed a mushroom to grow big. He ran through the Mushroom Kingdom smashing brick blocks along the way. At the end of the world Bowser was waiting on a bridge above the lava.",
    // Zelda
    "Link woke up in a strange land without his sword or shield. A fairy named Navi told him the Great Deku Tree was in danger and needed his help. He grabbed the kokiri sword from the chest and entered the forest dungeon.",
    // Naruto
    "Naruto failed the ninja graduation exam three times but never gave up trying. He learned the forbidden shadow clone jutsu in one night to prove himself. The village finally recognized him as a real ninja after he stopped Mizuki.",
    // Dragon Ball
    "Goku found the four star dragon ball that his grandpa had left him as a child. He met Bulma on a road and she had a machine that could find the other seven. They set off together not knowing the danger that lay ahead.",
    // Need for Speed
    "The city lights reflected off the wet streets as the race began at midnight. A rookie driver in an old tuned coupe lined up against the fastest crew in town. When the signal dropped the tires screamed and the chase was on.",
    // Fallout
    "The vault door opened for the first time in two hundred years and sunlight poured in. A lone wanderer stepped out into the wasteland with nothing but a pip boy on their wrist. The ruined world stretched out in every direction waiting to be explored.",
    // League of Legends
    "Two teams of five champions gathered on the rift ready for battle. Each player chose a role and moved toward the lane they would defend. The first turret fell within ten minutes and the real fight began.",
    // Monster Hunter
    "The hunting horn sounded at dawn and the party of four gathered at the gate. Their target was a Rathalos that had been burning the nearby village fields. They packed rations and potions then disappeared into the ancient forest.",
    // Gran Turismo
    "The starting grid was full of the finest machines from around the world. A young driver sat in a secondhand coupe that he had tuned himself in his garage. When the flag dropped he pushed the engine to its limit and held his line.",
    // Persona
    "A new student arrived in the city on a rainy night with just one bag. He had a transfer record that other students whispered about in the halls. On his first day at school a strange app appeared on his phone by itself.",
    // Hyper Light Drifter
    "The Drifter coughed blood but kept moving through the ruins of the old world. Ancient machines still hummed with power that no one alive could explain. The sword at his side glowed faintly as he pushed deeper into the forgotten lands.",
    // Minecraft
    "A player punched the first tree and collected enough wood to make a crafting table. Before night fell they built four walls and a roof to survive the darkness. In the morning they dug down looking for iron and found a cave full of coal.",
    // Sonic
    "Sonic ran through the green hill zone without slowing down for a single second. He collected rings along the path and smashed a row of robots with a spin dash. Dr Eggman appeared in a machine at the end and the fight began.",
    // Final Fantasy
    "Four warriors of light each holding a darkened crystal gathered at the edge of the world. The prophecy said they were chosen to restore the light and defeat the chaos. None of them knew each other yet but the journey ahead would change that.",
  ],

  medium: [
    // Pokemon
    "The Pokemon League was more than a tournament — it was the culmination of a journey across eight cities, each guarded by a gym leader with mastery over a single type. Ash had lost to the Elite Four before and knew this time required not just strong Pokemon but the bond forged through every battle and every loss. Pikachu stood at the center of that bond, refusing to evolve because the strength between them needed no stone to prove it.",
    // Mario
    "Bowser had kidnapped Princess Peach not simply out of cruelty but because ancient Koopa legend held that a union between the Koopa King and the princess of the Mushroom Kingdom would grant dominion over both realms. Mario was just a plumber from Brooklyn who had tumbled into this world through a pipe, yet somehow he kept standing between Bowser and his ambition. Every castle Mario cleared revealed a Toad bearing the same message — the princess was always in the next one.",
    // Zelda
    "The Triforce existed at the point where the three goddesses departed the world after its creation, a relic of pure divine power that granted the wish of whoever touched it first. If a person of balanced wisdom, power, and courage claimed it, the world would flourish. But the Gerudo thief Ganondorf had waited years for the Sacred Realm to open and he did not carry a balanced heart when his hand finally reached the golden triangle.",
    // Naruto
    "The Nine-Tails attack on the Hidden Leaf Village was not simply a monster's rampage but the result of a masked man who had used a powerful genjutsu to seize control of the fox and aim its hatred at the village. The Fourth Hokage gave his life to seal the beast inside his newborn son, splitting the demon's chakra between his own soul and the child. Naruto grew up knowing none of this, only that the village looked at him with fear and kept their distance.",
    // Dragon Ball
    "The Saiyan race was nearly extinct because Frieza had destroyed Planet Vegeta out of fear that a legendary Super Saiyan warrior of myth would one day rise and overthrow him. Two Saiyan infants survived by chance: Vegeta, son of the king, raised among Frieza's forces, and Kakarot, sent to Earth and given the name Goku. The irony that Frieza's greatest fear was the very thing his genocide had set in motion would not become clear until the two survivors stood before him on Namek.",
    // Need for Speed
    "The underground racing scene operated in the hours between midnight and dawn, when police patrols were thinner and the city's long straights belonged to those fast enough to claim them. Reputation was the only currency that mattered and it was earned one race at a time against crews who had been running these streets for years. A new driver with nothing but a stock car and a reckless willingness to push every corner to its absolute limit was about to make the veteran crews very uncomfortable.",
    // Fallout
    "The Great War lasted only two hours but two hundred years of fallout followed. The vaults were sold to citizens as shelters but most were never meant to save anyone — they were experiments designed to study human behavior under controlled catastrophic conditions. The people who emerged into the wasteland centuries later did so into a world where the institutions that caused the war had simply mutated into new factions wearing different flags over the same ambitions.",
    // League of Legends
    "The Summoner's Rift was not merely a battlefield but a convergence point for champions from across Runeterra, beings whose conflicts and histories stretched across wars, betrayals, and centuries. Demacia and Noxus sent their finest warriors to the same map where a mage who shattered reality stood in the same lane as a robot searching for a soul. The lore that underpinned each match was a continent's worth of war compressed into forty minutes of objective-focused violence.",
    // Monster Hunter
    "The Guild had catalogued hundreds of species across the known world but the elder dragons remained the greatest mystery, creatures so ancient they were considered natural disasters rather than prey. A hunter who aspired to face them first had to prove themselves against smaller apex predators, building armor from the very monsters that had once nearly killed them. The ecology of the monster world was not a hierarchy of predator and prey but a web where every death fed something else.",
    // Gran Turismo
    "The GT World Series had produced legends who started exactly where most drivers still stood — in underpowered regional vehicles running against faster machines on borrowed time. The manufacturer teams recruited from these ranks because raw mechanical instinct could not be taught in a simulator and the drivers who learned on inferior equipment developed a sensitivity to the car that factory drivers often lacked. A championship run in a privateer vehicle against works teams was considered impossible by everyone except the people actually attempting it.",
    // Persona
    "Shadows were not enemies in any simple sense — they were the repressed contents of the human psyche given form inside the Metaverse, a cognitive world shaped by humanity's distorted desires. The Phantom Thieves did not destroy their targets but stole the distorted desires from their hearts, forcing a change of heart that the real world registered as a sudden confession. The moral ambiguity of rewriting someone's personality without consent haunted the team even as the society they operated in gave them no lawful alternative.",
    // Hyper Light Drifter
    "The civilization that preceded the Drifter's world had reached a technological apex that ended in catastrophe, leaving ruins so advanced they resembled temples more than machines. The Immortal Tall — creatures of immense power — had been bound beneath the earth at tremendous cost but the seals were weakening as the generations who remembered how to maintain them died out. The Drifter carried a disease that was slowly killing them, a disease that seemed connected to the same ancient energy that had destroyed the world once before.",
    // Dark Souls
    "The Age of Fire was sustained not by the natural order of the world but by the First Flame, which required souls of great power to be sacrificed to it as it dimmed over centuries. Lords who had linked the fire in past ages had become legends, but the cycle itself was never questioned until the moment a hollow undead found themselves at the kiln and faced the choice of whether to continue the age of fire or usher in an age of dark. The architecture of the world — dead gods, hollow servants, kingdoms built on top of kingdoms — was the physical record of how many times someone had made that choice before.",
    // Halo
    "The Forerunners were the most advanced civilization the galaxy had ever produced, yet they chose to fire the Halo Array — weapons capable of eliminating all life within their range — to stop the Flood from consuming everything. The rings were not weapons of war but of desperation, a choice made by beings who had exhausted every other option and faced extinction. Humanity discovered them tens of thousands of years later with no knowledge of what the structures were, why they had been built, or why the caretakers left behind seemed to be waiting for them specifically.",
    // Elden Ring
    "The Elden Ring was the foundational law of the Lands Between, a construct of the Outer God known as the Greater Will that had shattered when Queen Marika struck it in grief and rebellion. The demigod children who inherited its shards each became corrupted by that fragment of rotten grace and waged a war across the continent that left the world broken and its people hollow. A Tarnished — someone who had lost the grace of the Erdtree and been exiled to the outer lands — was being called back not because they were chosen but because everyone more qualified was already dead.",
  ],

  hard: [
    // Pokemon
    "The relationship between Pokemon and humanity as depicted across the franchise's canonical mythology is not one of domestication but of an ancient covenant predating recorded civilization, with Arceus — the cosmological originator of the Pokemon universe — having shaped both the physical world and the life forms within it simultaneously. The Pokedex entries, when read cumulatively across generations, describe creatures with cognitive complexity, emotional range, and metaphysical properties that render the trainer-battle paradigm philosophically incoherent unless interpreted as ritualized combat between consenting parties operating within a cultural framework invisible to outside observers. The recurring tension in the narrative between figures like N, who advocate abolishing the trainer system, and the game's implicit endorsement of bonding through competition, is never resolved because the franchise's commercial structure requires the contradiction to remain productive rather than be dissolved through genuine ethical inquiry.",
    // Persona
    "The Jungian architecture underlying the Persona series is not merely aesthetic decoration but the structural logic that determines how the Metaverse functions as a cognitive externalization of collective psychological repression. Shadows represent the Jungian shadow concept — the disowned contents of the self — while Personas literalize the mask Jung described as the social interface the ego presents to the world, now weaponized as a supernatural defense mechanism. The recurring antagonists across the series are not simply villains but distillations of Jungian archetypes given narrative form: the Trickster, the Senex, the Anima, with the protagonist functioning as the Hero archetype who integrates rather than suppresses the shadow, achieving individuation through confrontation rather than avoidance.",
    // Hyper Light Drifter
    "Hyper Light Drifter communicates its entire narrative — the rise and fall of an advanced civilization, the nature of the Immortal Tall, the Drifter's terminal illness, and the cyclical pattern of technological hubris producing existential catastrophe — without a single line of conventional dialogue, relying instead on environmental storytelling, symbolic imagery, and an iconographic visual language that demands interpretive engagement rather than passive reception. The game's creator Alex Preston designed it while managing a serious heart condition, a biographical context that renders the Drifter's deteriorating body and the ruins of a world that could not be saved despite its achievements into something simultaneously personal and mythological. The deliberate ambiguity of the ending — whether the Drifter transcends the cycle or simply becomes another monument to it — refuses the consolation of resolution in a way that most commercial game narratives are structurally prohibited from doing.",
    // Fallout
    "The Fallout series constructs its post-apocalyptic world not as a simple critique of nuclear anxiety but as a sustained satire of mid-twentieth century American exceptionalism, using the retrofuturistic aesthetic of a 1950s vision of the future that never course-corrected to illustrate how ideological frameworks outlast the material conditions that produced them. The Great War functions not as a cautionary tale about nuclear weapons specifically but about the impossibility of a civilization recognizing its own terminal trajectory from within, since the cultural products of pre-war America depicted throughout the games show a society that had aestheticized its own path to destruction into optimistic consumerism. The factions that emerge in the wasteland — the Brotherhood of Steel's technological hoarding, the Institute's transhumanist detachment, Caesar's Legion's historical cosplay — are not random power structures but each represents a coherent philosophical response to civilizational collapse that illuminates a different failure mode of human ideological thinking.",
    // Zelda
    "The Triforce as a cosmological concept across the Legend of Zelda series encodes a specific philosophical claim about the nature of power and its relationship to personal virtue, positing that absolute power granted to a being of imbalanced character will always fracture along the lines of that imbalance, distributing itself according to whichever virtue the claimant most embodies. Ganondorf's repeated acquisition of only the Triforce of Power is therefore not simply a narrative limitation but a theological statement about the relationship between desire, restraint, and what the goddesses considered the highest virtue. The recurrence of Ganon across timelines — his literal reincarnation encoded into the world's structure as a consequence of a single act of ambition in the Sacred Realm — frames the entire franchise as a meditation on whether evil is a property of individual actors or a structural feature of a world built around a power that cannot be equitably distributed.",
    // Naruto
    "The thematic core of Naruto is not the individual hero's journey but a generational trauma narrative in which systemic failures of institutional power — the village system, the concept of the hidden village itself, the weaponization of children through the shinobi academy — produce cycles of violence that individual acts of will cannot break without simultaneously dismantling the structures that made those acts necessary. Obito's transformation from idealistic child to nihilistic villain mirrors Naruto's own trajectory point for point, with the divergence between them hinging not on moral character but on the presence or absence of meaningful social connection at the critical moment of loss. The Infinite Tsukuyomi that Madara seeks is the logical conclusion of the series' central tension — a world without the pain that connection produces is indistinguishable from a world without connection itself, which is what Naruto spends the entire narrative arguing against through action rather than philosophy.",
    // Dragon Ball
    "The power scaling narrative of Dragon Ball Z, frequently criticized as an escalating absurdity, functions coherently when understood as a deliberate deconstruction of the martial arts genre's premise that individual strength is the ultimate expression of personal virtue. Each arc systematically dismantles the previous ceiling of meaningful power and replaces it with a new one, not to celebrate the new ceiling but to demonstrate that the philosophical framework attached to power — that strong people deserve to win and winners deserve their strength — becomes increasingly indefensible as the stakes become more cosmological. Goku's persistent naivety in the face of genuine evil, his refusal to kill Frieza when he had the opportunity, his decision to give Cell a senzu bean, are not character flaws the narrative endorses but the series working through what it actually means to hold the belief that fighting spirit is a moral good when fighting spirit becomes capable of erasing entire solar systems.",
    // League of Legends
    "Runeterra as a constructed fictional geography represents one of the most ambitious world-building projects in competitive game history, assembling a continental mythology across region-specific lore documents, comics, the animated series Arcane, and champion biography pages that collectively form a coherent historical record of a world defined by the collision between emerging nation-states and magical forces that predate human civilization. Arcane specifically recontextualized Jinx and Vi from their original shallow designs into the central figures of a class conflict narrative set in Piltover and Zaun that used the fantasy setting to explore gentrification, institutional corruption, and the way systemic violence deforms the psychology of those subjected to it across generations. The decision to expand the IP through multiple game genres — strategy, card game, fighting game, role-playing game — reflects a recognition that a world this internally consistent generates sufficient narrative gravity to sustain multiple entry points without requiring players to engage with the source material in any canonical order.",
    // Monster Hunter
    "The ecological philosophy embedded in Monster Hunter's design is more sophisticated than its action-game exterior suggests, constructing a biome-level food web across which every hunted creature occupies a specific niche, and where the consequences of removing an apex predator are modeled with enough systemic fidelity that players who pay attention to field notes and region descriptions can trace how one hunt destabilizes the behavioral patterns of adjacent species. Elder Dragons occupy the cosmological apex of this system not simply because they are powerful but because they are environmental forces — Kushala Daora's wind fields affect weather patterns, Chameleos redistributes moisture across ecosystems, Teostra's powder functions as a chemical defense that is simultaneously a fire risk to the vegetation it inhabits. The franchise's refusal to frame any creature as evil — every monster is behaving according to its ecological programming — constitutes a quiet but persistent argument against the anthropocentric moral framework that most action games use to justify their violence.",
    // Need for Speed
    "The Need for Speed series' cultural significance exists at the intersection of automotive fetishism and a specifically American mythology of freedom-through-velocity that became commercially durable precisely because it gave players access to machines and spaces that urban geography and economic stratification make inaccessible in ordinary life. The Underground entries in particular captured a specific cultural moment in early-2000s tuner culture — itself a hybrid product of Japanese car modification aesthetics filtered through Southern California street racing communities — and projected it onto a fictional city that compressed all of its visual codes into a perpetual neon-saturated midnight that functioned as the genre's definitive aesthetic register. The shift in later entries toward police pursuit and open world design reflected the franchise's recognition that the fantasy was not purely about the cars but about operating outside institutional boundaries, with law enforcement functioning less as antagonist and more as the environmental pressure that gives the fantasy its transgressive texture.",
    // Gran Turismo
    "Gran Turismo's foundational design philosophy, articulated by Kazunori Yamauchi across decades of interviews, held that the game should function as a form of automotive education rather than entertainment in the conventional sense, with the simulation fidelity serving a pedagogical purpose: to give players an experiential understanding of vehicle dynamics that text-based explanation cannot convey. The licensing test system that gate-keeps progression in the earlier titles is not a conventional difficulty curve but an explicit curriculum, requiring players to demonstrate competence in braking zones, weight transfer, and line selection before the game grants access to higher-performance machinery. This philosophy creates a tension between the simulation's fidelity and commercial accessibility that the franchise has never fully resolved, with each entry representing a different calibration point between the vision of a complete driving simulator and the practical reality that most players want to feel fast rather than understand the physics that produce speed.",
    // Dark Souls
    "The architecture of the Dark Souls world is not metaphorical but literal historiography — the vertical geography of Lordran, with its buried cities beneath cities and its gravitational impossibilities, is the physical record of successive civilizations that rose, linked the fire, fell into ash, and were built over by the next age without any of the accumulated history being discarded or processed. The enemies the player fights are not invaders or monsters in the conventional sense but the remnants of previous cycles who have become hollow — their purpose outlasted their sanity — and yet continue enacting the behavioral patterns of their former roles out of a compulsion that substitutes for the identity the curse has dissolved. FromSoftware's decision to deliver this narrative through item descriptions, environmental detail, and NPC conversations that each player will encounter in different order and completeness means that the experience of the lore is itself an enactment of the game's theme: meaning assembled from fragments by an individual who will never have access to the complete picture.",
    // Elden Ring
    "Elden Ring's cosmological structure introduces a layer of theological complexity absent from earlier FromSoftware titles by positing not one divine source of order but multiple competing Outer Gods who extend their influence into the Lands Between through proxies — Marika for the Greater Will, the Formless Mother through Mohg, the Scarlet Rot through Malenia — each promoting a fundamentally different vision of what the world should become and each willing to use human suffering as an instrument toward that end. The shattering of the Elden Ring by Marika herself represents an act of divine ambivalence or rebellion that the game never fully explains, leaving players to reconstruct her motivations from items and architecture in a world that has already been permanently altered by whatever she felt in that moment. George R.R. Martin's involvement in constructing the pre-history means that the backstory the player can never directly witness — the Shattering, the Elden Lord era, the original sin that set the events in motion — carries the structural density of literary fantasy world-building rather than the functional minimum required to justify a game's setting.",
    // Halo
    "The Forerunner civilization's decision to fire the Halo Array constitutes the franchise's central moral paradox: an act of genocide committed by the most technologically advanced species in galactic history against all sentient life including themselves, justified by the utilitarian calculus that the Flood's consumption of all biomass represented a worse outcome than a temporary extinction event after which life would be reseeded from the Ark. The Didact's later opposition to this calculus — his advocacy for the Composer, which digitizes rather than destroys consciousness — is positioned by the narrative as a villainous alternative, yet the game never successfully argues that digitized survival is categorically inferior to the complete annihilation that the Halo solution requires. Master Chief's operational role as a weapon optimized for military effectiveness allows the franchise to defer this philosophical tension indefinitely because his character is defined by a will to act rather than a capacity for the kind of reflection the question demands.",
    // Final Fantasy
    "The recurrence of crystals, light warriors, and elemental imbalance across the Final Fantasy mainline titles represents not a failure of creative originality but a deliberate mythological vocabulary that the series uses as a shared symbolic substrate even when the individual narratives diverge radically in tone, setting, and character. Final Fantasy VII's Jenova and the Lifestream recontextualize this vocabulary through a biological and ecological lens — the planet as living organism, the Mako economy as literal vampirism of planetary life-force — producing a critique of industrial capitalism that was sufficiently abstracted into fantasy that its political content remained commercially viable. The Cloud Strife arc, which concerns the constructability of personal identity when memory has been systematically replaced, anticipates by nearly a decade the philosophical discourse around memory, authenticity, and self-narrative that would become central to academic psychology and philosophy of mind in the early twenty-first century.",
  ],
};

export function getRandomText(difficulty: Difficulty): string {
  const pool = textPools[difficulty];
  return pool[Math.floor(Math.random() * pool.length)];
}
